### ISSUE TITLE
Add DD_MERGE_XRAY_TRACES to Datadog Construct

### ISSUE THREAD

**Issue by ejubber** [DataDog/datadog-cdk-constructs#101]
## Expected Behavior
DD_MERGE_XRAY_TRACES is a settable parameter on the Datadog construct to allow for serverless trace merging per this documentation: https://docs.datadoghq.com/serverless/distributed_tracing/serverless_trace_merging/ 

## Actual Behavior
There is no way to set this variable for all lambdas in my stack. As such, there is no way to merge the traces from Datadog and X-Ray for my AWS step functionsw. 

## Steps to Reproduce the Problem

  1. Create new Datadog CDK construct
  2. No ability to add DD_MERGE_XRAY_TRACES
 
## Specifications

  - Datadog Lambda Layer version:  76
  - Node version: 14
  
## Stacktrace
  
  ```
  const datadog = new Datadog(this, "Datadog" + branch, {
          nodeLayerVersion: 76,
          extensionLayerVersion: 21,
          apiKey: datadogAPIKey.secretValueFromJson('DatadogAPIKey').toString(),
          captureLambdaPayload: true,
        })
  ```

**Comment by DarcyRaynerDD** [comment]
Hey @ejubber , as a work around, you could manually set the DD_MERGE_XRAY_TRACES=true on your functions.
eg.
```
const myFunction = new NodejsFunction(this, id, {
  // setting environment variables 👇
  environment: {
    DD_MERGE_XRAY_TRACES: 'true',
  },
  // ...
});
```
We are working on an alternative to x-ray tracing for step functions. If that's something you would be interested in, you can DM me on our [public slack](https://chat.datadoghq.com/).

**Comment by coltnz** [comment]
Hi, is there a workaround for Step Function Activities. I have a step function calling on premise Activities instrumented with dd_trace.
