### ISSUE TITLE
Forwarder Subscription Filters Should Not Create Lambda Permissions

### ISSUE THREAD

**Issue by jglien** [DataDog/datadog-cdk-constructs#124]
The current implementation below uses the [default behavior of creating a Lambda permission per log group](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs_destinations.LambdaDestinationOptions.html#addpermissions) on the target lambda (the forwarder) which causes a deployment failure when the number of lambdas/log groups is large enough. The specific error will be:

`The final policy size ({{ size }}) is bigger than the limit (20480)`

https://github.com/DataDog/datadog-cdk-constructs/blob/ebefde300e4c732d8a41545dcfda07bdbe84c9f3/v2/src/forwarder.ts#L28

https://github.com/DataDog/datadog-cdk-constructs/blob/ebefde300e4c732d8a41545dcfda07bdbe84c9f3/v2/src/forwarder.ts#L41

Since the forwarder already has the permission allowing all log groups in the account and region trigger it, the solution is simply to pass `{ addPermissions: false, }`, or make this configurable.

**Comment by astuyve** [comment]
Hi, thanks @jglien! We've triaged this issue and assigned a reviewer who should be able to help you out soon.

In the meantime, I'd suggest using the Datadog Lambda Extension instead of the forwarder. The Extension is our default and recommended integration for Lambda, and will also get you around this issue.

You can do this easily by specifying `extensionLayerVersion` like this:
```js
    const datadog = new Datadog(this, "Datadog", {
      nodeLayerVersion: 83,
      extensionLayerVersion: 29,
      apiKey: '<your key>',
    })
    datadog.addLambdaFunctions([handler])
```

**Comment by jglien** [comment]
@astuyve We have been using the Lambda extension for a while but are switching to the forwarder for two reasons: to improve our lambda performance by offloading the logging overhead and removing a layer, and to allow us to have other log groups send their logs the same way the lambdas do, rather than having multiple integrations to maintain.
Why is the extension recommended over the log group forwarder integration? I don't see that discussed in the docs.

**Comment by astuyve** [comment]
@jglien Interesting! Do you find yourself hitting the maximum 5 layers on many of your functions?

We recommend the Extension over the Forwarder for use with Lambda, and the reasoning is laid out in the [docs](https://docs.datadoghq.com/serverless/guide/extension_motivation/).

Please do let me know if you have further questions. Thanks!

**Comment by jglien** [comment]
@astuyve ah thanks. To be very clear, does "cost" in the quote below mean $$$ or performance cost? Because that would be very surprising if offloading sending logs to the forwarder would somehow _increase_ performance overhead.
> Based on Datadog’s latest benchmarking results, the cost overhead is always lower (or about the same when reporting data from remote regions) when using the Lambda extension versus the Forwarder.

We are not hitting the maximum layers, this is just an optimization. The Datadog layers are currently our only ones and we can remove both layers by switching to the forwarder and bundling the Datadog package with our apps.

**Comment by astuyve** [comment]
Good question, that quote specifically is in the form of dollar cost, but let's unpack the performance cost a bit as well.

I'm going to focus on logs here, as that's what you have called out. But I'm happy to expand on metrics or traces as well.

The passing of logs between your function and the extension is done by implementing the [Logs API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html) from the Lambda runtime. So compared to the forwarder, this will be more performant as there's no serializing to cloudwatch, polling on the log group, and then triggering the forwarder. In other words: *your function execution does not wait on a round-trip request to Datadog's log intake before returning.*

Communication between the Extension and Datadog happens asynchronously from your function execution, so while you may see your overall function duration is higher with the Extension, that is often caused by the Extension flushing to Datadog _after_ your function has already returned to the user/caller. This is documented [here](https://docs.datadoghq.com/serverless/libraries_integrations/extension/#overhead).

We surface this to users in the form of two metrics:
- `aws.lambda.enhanced.runtime_duration` (which measures only the function execution time, minus any extensions)
and
- `aws.lambda.enhanced.post_runtime_duration` (which measures the time spent from after the function has returned to the caller, until any extensions finish)

You can learn more about these [in the docs](https://docs.datadoghq.com/serverless/enhanced_lambda_metrics/)

**Comment by IvanTopolcic** [comment]
👋 Hey @jglien ! Thanks for the PR!

I can confirm that I do see resource policies on the forwarder that give it the logs service access to trigger the function. This means that you should only need to add a subscription to the log group (or do nothing if you have the option to automatically subscribe enabled in the Datadog integration on the website).

Could you just let me know which policy is becoming too large? I've tried testing the PR and setting `createForwarderPermissions` to true but I don't see which policy is being updated. I'm guessing the Datadog forwarder policy is being updated, but I don't see any changes when I deploy a function with the CDK and this option enabled. Do you have an example of your too-large policy, maybe truncated with some redacted information?

**Comment by jglien** [comment]
Hi @IvanTopolcic! Thanks for taking a look at this.

The policy that is too large is the resource based policy on the forwarder (you can find it by going to the forwarder in the console -> configuration -> permissions -> "View policy" on Resource-based policy statements). Ours looks like this right now if we attach a single log group with `addForwarderToLogGroups()`:

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "datadog-forwarder-S3Permission-1WQKH6G2LMKTF",
      "Effect": "Allow",
      "Principal": {
        "Service": "s3.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:***:function:***-dd-forwarder",
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "***"
        }
      }
    },
    {
      "Sid": "datadog-forwarder-SNSPermission-KQYT8AME9VE8",
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:***:function:***-dd-forwarder",
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "***"
        }
      }
    },
    {
      "Sid": "datadog-forwarder-CloudWatchEventsPermission-IG0EIMA7S9Z2",
      "Effect": "Allow",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:***:function:***-dd-forwarder",
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "***"
        }
      }
    },
    {
      "Sid": "datadog-forwarder-CloudWatchLogsPermission-3JBJJZISYHWG",
      "Effect": "Allow",
      "Principal": {
        "Service": "logs.us-east-1.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:***:function:***-dd-forwarder",
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "***"
        }
      }
    },
    {
      "Sid": "my-env-sor-v2-sst-datadog-TEST789logc1c97abaDatadogSubscriptionFilter31581238CanInvo-1VFBWVJBOSN86",
      "Effect": "Allow",
      "Principal": {
        "Service": "logs.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:***:function:***-dd-forwarder",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:logs:us-east-1:***:log-group:/aws/rds/cluster/aurora-cluster-my-env/postgresql:*"
        }
      }
    }
  ]
}
```

Notice how the last policy is for the log group we added and is unnecessary because of the preceding policy. That's the bug my pr fixes. This forwarder has only had one log group attached to it, but if enough log groups/lambdas without extension are added (and presumable most of your users have more than enough), the policy JSON becomes larger than the hard limit of `20480` characters because it's creating a policy per log group.

Here are the steps to demonstrate this behavior with the PR:

1. `yarn watch` v2
2. Set configuration in `v2/src/sample/index.ts` to:
    ```ts
    {
      nodeLayerVersion: 62,
      pythonLayerVersion: 46,
      // extensionLayerVersion: 10,
      forwarderArn: process.env.FORWARDER_ARN,
      createForwarderPermissions: false,
      enableDatadogTracing: true,
      flushMetricsToLogs: true,
      apiKey: process.env.API_KEY,
      site: "datadoghq.com",
    }
    ```
1. Run `npx cdk --app lib/sample/index.js synth`
1. Open `v2/cdk.out/ExampleDatadogStack.template.json`
1. Search for the string: `AWS::Lambda::Permission`, note count `12`
1. Change to `createForwarderPermissions` to `true` and run `npx cdk --app lib/sample/index.js synth`
1. Search for the string: `AWS::Lambda::Permission`, note count increased to `20` with new permissions for each individual log group

As mentioned above, this is the [default behavior](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs_destinations.LambdaDestinationOptions.html#addpermissions) of the `LambdaDestination` contruct.

**Comment by IvanTopolcic** [comment]
I'm not able to reproduce this on my end. I've created a minimal `sample/lambda/index.ts` to try to reproduce the issue with just one log group. What should be happening is that the log group should be given permission to execute the forwarder function, as per the issue. Here's my `sample/lambda/index.ts`:

```typescript
import { App, Stack, StackProps } from "aws-cdk-lib";
import { LogGroup } from "aws-cdk-lib/aws-logs";
import { Datadog } from "../index";

export class ExampleStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);

    const restLogGroup1 = new LogGroup(this, "restLogGroup1");

    const datadogCDK = new Datadog(this, "Datadog", {
      forwarderArn: process.env.FORWARDER_ARN,
      createForwarderPermissions: true,
    });

    datadogCDK.addForwarderToNonLambdaLogGroups([restLogGroup1]);
  }
}

const app = new App();
new ExampleStack(app, "Stack");
```

I compile this and run `cdk --app lib/sample/index.js synth`, but I'm not seeing any permissions for log groups in my output in `cdk.out/Stack.template.json`. In fact, I don't see any `AWS::Lambda::Permission` statements in here. Is there something that I'm missing here?

**Comment by jglien** [comment]
@IvanTopolcic Hmm your minimal one doesn't generate it for me either, like the unit tests. However, it certainly does for the existing sample. Did you try a `synth` of the existing sample following the instructions in my previous comment?

**Comment by IvanTopolcic** [comment]
Yeah I followed your instructions but didn't see any InvokeFunction permissions on cloudwatch logs in the output either.

**Comment by IvanTopolcic** [comment]
Not being able to reproduce this aside, this also seems like it would be a breaking change since that permission on the forwarder was only added in [version 3.5.0](https://github.com/DataDog/datadog-serverless-functions/commit/10b529af112ce9720ecc73c1b4952b488c947ba4), meaning that any users who using <3.5.0 who deployed a new CDK function with this change would notice log forwarding breaking for their CDK functions.

Because this is a breaking change, we're going to discuss the best approach here. We still do have a few users using <3.5.0 of the forwarder, and we need to figure out if this would be worth it.

Really appreciate the PR and appreciate your patience 🙏

**Comment by IvanTopolcic** [comment]
I just had a talk with our team and we're going to go ahead with this as a breaking change and cut a new major release. I'm going to try and dig into why I can't reproduce this locally and get back to you @jglien.

**Comment by jglien** [comment]
@IvanTopolcic Sorry for the late reply. I was incredulous that you couldn't reproduce it, so I tried a few things and discovered that, for an unknown reason, if `StackProps.env.account` is assigned a value, we get the extra permission.

e.g.
```ts
import { App, Stack, StackProps } from "aws-cdk-lib";
import { LogGroup } from "aws-cdk-lib/aws-logs";
import { Datadog } from "../index";

export class ExampleStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);

    const restLogGroup1 = new LogGroup(this, "restLogGroup1");

    const datadogCDK = new Datadog(this, "Datadog", {
      forwarderArn: process.env.FORWARDER_ARN,
      createForwarderPermissions: true,
    });

    datadogCDK.addForwarderToNonLambdaLogGroups([restLogGroup1]);
  }
}

const app = new App();
const env = {
  account: process.env.CDK_DEFAULT_ACCOUNT, // Comment this line and the permission goes away
  region: "sa-east-1"
};new ExampleStack(app, "Stack", {env});
```

We troubleshooted a bit but can't figure out why this behavior happens.

**Comment by IvanTopolcic** [comment]
Not a late reply at all -- and thank you so much for the reproduction! Definitely stumped me as I didn't see it referenced anywhere. I'll re-deploy Tuesday and merge the fix in once I confirm it's working.

And I personally vouch for the extension but I can see how the forwarder can be simpler to use. If you have any feedback around the extension we'd definitely love to hear it

**Comment by IvanTopolcic** [comment]
Fixed! Thanks for the report!
