### ISSUE TITLE
Property enableMergeXrayTraces missing ?

### ISSUE THREAD

**Issue by PierreKiwi** [DataDog/datadog-cdk-constructs#133]
## Expected Behavior

The documentation indicates that the `enableMergeXrayTraces` property exists for the `Datadog` construct.

## Actual Behavior

The property `enableMergeXrayTraces` is not found.

## Steps to Reproduce the Problem

  1. Install the latest version of the construct (v2)
  2. Create a new `Datadog` and try to set `enableMergeXrayTraces`
  3. Synthesize the stack.

## Specifications

  - Datadog Lambda Layer version:  35
  - Node version: v16.15.1
  
## Stacktrace
  
  ```
  TSError: ⨯ Unable to compile TypeScript:
ApiGatewaySpecRestApiPerMicroserviceStack.ts:194:7 - error TS2345: Argument of type '{ apiKeySecretArn: string; captureLambdaPayload: false; env: string; enableDatadogLogs: false; enableMergeXrayTraces: boolean; extensionLayerVersion: number; pythonLayerVersion: number; service: string; site: string; version: string; }' is not assignable to parameter of type 'DatadogProps'.
  Object literal may only specify known properties, and 'enableMergeXrayTraces' does not exist in type 'DatadogProps'.
  ```

**Comment by blytheaw** [comment]
I am also experiencing this issue with TypeScript CDK setup using the latest v2 construct

**Comment by sfirrin** [comment]
Hi @PierreKiwi and @blytheaw, thanks for opening this issue

`enableMergeXRayTraces` has been implemented in https://github.com/DataDog/datadog-cdk-constructs/pull/127 and should now be working as of the release of https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-1.2.0

Please give it a try and let us know if you run into any issue
