### ISSUE TITLE
Bump @aws-cdk/aws-lambda-python-alpha version to latest #298 

### ISSUE THREAD

**Issue by ddhanak** [DataDog/datadog-cdk-constructs#145]
## Expected Behavior
Whenever we install the datadog construct with the latest aws-lambda-python-alpha package, it should not fail with a dependency error

## Actual Behavior
Fails with dependency error

## Steps to Reproduce the Problem

  1. install the latest `@aws-cdk/aws-lambda-python-alpha` package
  1. install the `datadog-cdk-constructs-v2` package

## Specifications

  - Datadog Lambda Layer version: n/a
  - Python version: n/a
  
## Stacktrace
  
  ```
  npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdk@0.1.0
npm ERR! Found: @aws-cdk/aws-lambda-python-alpha@2.59.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!   @aws-cdk/aws-lambda-python-alpha@"^2.59.0-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-lambda-python-alpha@"^2.24.0-alpha.0" from datadog-cdk-constructs-v2@1.2.0
npm ERR! node_modules/datadog-cdk-constructs-v2
npm ERR!   dev datadog-cdk-constructs-v2@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
  ```

**Comment by astuyve** [comment]
Hi, this is fixed with https://github.com/DataDog/datadog-cdk-constructs/pull/143 and the latest release https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-1.3.0

**Comment by ddhanak** [comment]
@astuyve my bad should have checked the releases!

**Comment by astuyve** [comment]
No problem at all! I saw your ticket in datadog-lambda-python and was going to reply there.

Thanks!
