### ISSUE TITLE
Add support for adding Java tracing layer

### ISSUE THREAD

**Issue by rgustafson-ie** [DataDog/datadog-cdk-constructs#153]
Please add support for the dd-java-trace layer.

Current workaround after calling `add_lambda_functions` is to additionally manually [add a LayerVersion](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/Function.html#aws_cdk.aws_lambda.Function.add_layers) and [add the environment variable](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/Function.html#aws_cdk.aws_lambda.Function.add_environment) AWS_LAMBDA_EXEC_WRAPPER, as per the[ Custom setup](https://docs.datadoghq.com/serverless/installation/java/?tab=custom) instructions.

Sort of like so:
```python
the_lambda_function = ...

datadog.add_lambda_functions([the_lambda_function])

dd_trace_layer_version = aws_lambda.LayerVersion.from_layer_version_arn(
    self, "DatadogTraceJavaLayer", f"arn:aws:lambda:{self.region}:464622532012:layer:dd-trace-java:8"
)
the_lambda_function.add_layers(dd_trace_layer_version)
the_lambda_function.add_environment('AWS_LAMBDA_EXEC_WRAPPER', '/opt/datadog_wrapper')
```

**Comment by thedavl** [comment]
Hi @rgustafson-ie, java tracing layer support has been added in the most recent releases: [v0.8.6](https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v0.8.6) & [v2-1.5.0](https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-1.5.0). The docs will be updated shortly to reflect these changes. To enable adding the java layer, add `java_layer_version=8` to your datadog cdk configuration.

Like so:
```
from datadog_cdk_constructs_v2 import Datadog

class PythonCdkAppStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        ...
        datadog = Datadog(
            self,
            "Datadog",
            java_layer_version=8,
            extension_layer_version=41,
```

Let me know if you have any further questions!

**Comment by thedavl** [comment]
The documentation (both here and in the [serverless java installation docs page](https://docs.datadoghq.com/serverless/installation/java/?tab=awscdk)) have been updated. I'm closing this issue, but please reach out if you have any questions!
