### ISSUE TITLE
Publish C# package to NuGet

### ISSUE THREAD

**Issue by msessa** [DataDog/datadog-cdk-constructs#165]
Due to this being a JSII library, we could expect packages to be provided for languages other than javascript and python.

Could you please enable publishing to a public NuGet repository?

Until a package is published for C#, any downstream library depending on `datadog-cdk-constructs-v2` is also blocked from packaging for C#

**Comment by tianchu** [comment]
@msessa Thanks for your feedback! Your request makes sense, but given that it's first time we heard about this requirement, we can't yet immediately prioritize the work. We will keep the issue open to collect requests from other users. 

If this requirement is business blocking for you, I recommend reaching out through your Datadog account executive to the Datadog serverless product team.

**Comment by msessa** [comment]
Hi @tianchu, I'll continue the conversation here since #164 is basically the same thing.

I can contact our account executive, but just FYI it's not a large amount of work to enable nuget/maven publishing.
You are already using projen's `AwsCdkConstructLibrary` class for this project so this can be easily enabled with `publishToMaven` and `publishToNuget`. Github itself provides capabilities to host those type of packages.

**Comment by Joestetz** [comment]
+1 This would be a big help and looks to be pretty low-hanging

**Comment by tianchu** [comment]
Unfortunately, despite some interests, I don't think that we have seen enough demand from others. Publishing a new package isn't very difficult, but maintaining them does add non-trivial overhead for the team. Closing the issue for now, but will reopen if the demand rises.
