### ISSUE TITLE
Extension layer should always be added regardless of addLayers prop

### ISSUE THREAD

**Issue by joshlartz** [DataDog/datadog-cdk-constructs#201]
As far as I can tell from the [docs](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=custom), there's no way to add the contents of the extension via a package; it must always be a layer. That means even if I opt out of layers because I instrument my function myself with the library packages, it won't work without the extension. 

This has caused me to need to use `getExtensionLayerArn()` and add the layer myself, which feels unnecessary. I'm willing to make the PR if you agree on what correct behavior is here.

**Comment by astuyve** [comment]
Hi @joshlartz - thanks so much for reaching out!

I see what you're saying, I believe in a similar project we use addLayers to refer only to the specific tracer layer(s) and then have a separate config option for addExtension.

This library would likely be a bit different as users have to manually specify which versions to include or exclude.

We'd generally happily accept a PR, but I want to ask the team if we need this config option at all? Maybe we go off of `extensionLayerVersion` or/and `<runtime>LayerVersion`?
We'll likely discuss this at length before merging/changing this behavior.

Thanks!
AJ

**Comment by duncanista** [comment]
Hey @joshlartz,

I'm going to proceed to close this issue since we didn't receive a response in a long time.
If you still have questions, or concerns. Please feel free to re-open this issue.

**Comment by joshlartz** [comment]
@duncanista I was actually waiting to hear back from DataDog here based on AJ's comment that it needed some internal approval. I can make the PR if the team agrees on the premise.

**Comment by samchungy** [comment]
Hey, also after this.

Looking to use just the extension but not the library layer. In the Serverless plugin there's an `addExtension` option which is separate from `addLayers`.

**Comment by purple4reina** [comment]
@joshlartz You are welcome to create the PR. We just added a similar feature in the datadog-cloudformation-macro so I feel like a similar change here would be appropriate.
