### ISSUE TITLE
Default `sourceCodeIntegration` to false

### ISSUE THREAD

**Issue by JustinLiang90** [DataDog/datadog-cdk-constructs#202]
## Expected Behavior

Set `sourceCodeIntegration` to `false` by default.

## Actual Behavior

Set `sourceCodeIntegration` to `true` by default if not specified when init DataDog 
CDK construct.

## Why

`sourceCodeIntegration = true` make the CDK will do full deployment every time.
This is because CDK will do build, bundle and file hash. And then compare the
hash with remote to see if any new changes. If not, CDK will output (no changes)
and skip the stack deployment. However, by default set to `true` breaks it.

**Comment by sfirrin** [comment]
Hi @JustinLiang90 thanks for opening this

We're going to work on reproducing and seeing if the full rebuild is necessary, ideally we would be able to avoid it without disabling the source code integration
