### ISSUE TITLE
aws-lambda-python-alpha is outdated

### ISSUE THREAD

**Issue by vhnguyenae** [DataDog/datadog-cdk-constructs#208]
Hi, 
Currently `aws-lambda-python-alpha` version is still on `2.63.0-alpha.0`,  which is quite outdated, since the newest version is already `2.92.0-alpha.0`. I ran into the issue since yesterday, my workaround is downgrading `aws-lambda-python-alpha` to `2.63.0-alpha.0` for my project (or using the flag --force or --legacy-peer-deps as suggested in the error report). Is it possible to bump the version from your library?

## Expected Behavior
`npm install` runs successfully

## Actual Behavior
`npm install` failed with error ERESOLVE

## Steps to Reproduce the Problem

  1. Declare aws-cdk as part of the dependencies in package.json (In my case I have:
 ```json 
"devDependencies": {
...
    "@types/node": "20.5.1",
    "aws-cdk": "^2.92.0",
    "datadog-cdk-constructs-v2": "^1.7.4",
...
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "~5.1.6"
  },
  "dependencies": {
    "@aws-cdk/aws-glue-alpha": "^2.92.0-alpha.0",
    "@aws-cdk/aws-lambda-python-alpha": "^2.92.0-alpha.0",
    "aws-cdk-lib": "2.92.0",
...
```  
  3. Run `npm install`
  

## Specifications

  - Datadog Lambda Layer version: v47
  - Node version: v18.16.0
  
## Stacktrace

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: datadog-cdk-constructs-v2@1.7.4
npm ERR! Found: @aws-cdk/aws-lambda-python-alpha@2.64.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!   @aws-cdk/aws-lambda-python-alpha@"^2.64.0-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-lambda-python-alpha@"^2.63.0-alpha.0" from datadog-cdk-constructs-v2@1.7.4
npm ERR! node_modules/datadog-cdk-constructs-v2
npm ERR!   dev datadog-cdk-constructs-v2@"^1.7.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @aws-cdk/aws-lambda-python-alpha@2.63.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!   peer @aws-cdk/aws-lambda-python-alpha@"^2.63.0-alpha.0" from datadog-cdk-constructs-v2@1.7.4
npm ERR!   node_modules/datadog-cdk-constructs-v2
npm ERR!     dev datadog-cdk-constructs-v2@"^1.7.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

  ```

**Comment by sfirrin** [comment]
Thanks for opening @vhnguyenae, we will bump this and update you here

**Comment by vhnguyenae** [comment]
awesome thank you @sfirrin  😁

**Comment by vhnguyenae** [comment]
@sfirrin thank you, bumping `aws-lambda-python-alpha` to `2.93` and `datadog-cdk-constructs` to `2-1.8.0` worked 😁
