### ISSUE TITLE
Lambda requires DD_API_KEY envar even though Datadog is already provided with apiKeySecret

### ISSUE THREAD

**Issue by bencaldwell** [DataDog/datadog-cdk-constructs#226]
## Expected Behavior
I expected that when I initialise the Datadog construct with an apiKeySecret it should use this to populate any envars related to the api key and set permissions to read the secret.

## Actual Behavior
I get errors in the lambda cloudwatch logs: 
DD_EXTENSION | ERROR | Unable to load trace agent config: you must specify an API Key, either via a configuration file or the DD_API_KEY env var

## Steps to Reproduce the Problem

  1. Create the datadog construct
```
      const datadogApiKeySecret = Secret.fromSecretPartialArn(
        this,
        'datadogApiKeySecret',
        props.envConfig.datadogApiSecretArn,
      );
      // add datadog integration - this is passed to the constructs so they can add the datadog layer to the lambdas
      this.datadog = new Datadog(this, "Datadog", {
        nodeLayerVersion: 99,
        extensionLayerVersion: 49,
        site: 'datadoghq.com',
        apiKeySecret: datadogApiKeySecret,
        env: `${props.envConfig.envName}`,
        version: props.deployName,
        captureLambdaPayload: true,
      });
```
  2. Create a lambda function
```
// Create a lambda function to create a transaction when triggered by an IoT rules
    this.myLambdaFunction = new NodejsFunction(this, 'myLambdaFunction', {
      entry: 'resources/lambda/handler.ts',
      handler: 'myHandler',
      vpc: props.vpc,
      securityGroups: [lambdaSecurityGroup],
      environment: {
        DD_SERVICE: 'myLambdaFunction',
        env: props.envConfig.envName,
      },
      logRetention: logs.RetentionDays.ONE_WEEK,
      timeout: cdk.Duration.minutes(1),
      tracing: lambda.Tracing.ACTIVE,
    });
    this.datadog.addLambdaFunctions([ this.myLambdaFunction ]);
```
  3. The logs show the error describe
  4. Add the DD_API_KEY envvar and it starts working
```
    ...
    environment: {
        DD_SERVICE: 'myLambdaFunction',
        DD_API_KEY: this.datadog.props.apiKeySecret?.secretValue.unsafeUnwrap() || '',
        env: props.envConfig.envName,
      },
    ...
```

## Specifications

  - Datadog Lambda Layer version: 49
  - Node version: 99
  - datadog-cdk-constructs-v2@1.9.0

**Comment by astuyve** [comment]
hi @bencaldwell, thanks for reaching out!

Can you enable debug logs and see what the error is? I'd also suggest verifying that your secret is not a JSON object but instead a plain stright.

Thanks!

**Comment by mbonig** [comment]
I'm experiencing the same issue.

 pythonLayerVersion: 87,
 extensionLayerVersion: 43,
 apiKeySecret: datadogSecret,
 
 If I go to the Lambda function and manually set the DD_API_KEY, the problems go away.

**Comment by astuyve** [comment]
Hi @bencaldwell, given Matt's update here and no response I'm going to close this for now but will happily take a second look if you have time to get back to us. Otherwise, please feel free to reach out to support with questions: support@datadoghq.com

Thanks!
