### ISSUE TITLE
Layer Dependency Management

### ISSUE THREAD

**Issue by samchungy** [DataDog/datadog-cdk-constructs#232]
Hey there,

I've come from using the serverless datadog plugin and was wondering if there was an equivalent way of getting updates for the datadog layer version?

We rely on renovate to update our dependencies and whilst the serverless plugin would keep our layers up to date there doesn't appear to be a similar mechanism to do so here.

How would you recommend we do that?

Cheers

**Comment by samchungy** [comment]
Another argument for not using layers ay :')

**Comment by ahammond** [comment]
Another argument for not using DD. So expensive, but...

**Comment by astuyve** [comment]
Hi @ahammond, thanks for reaching out. If you'd like this feature, feel free to leave an upvote or open a feature request with us! If you'd like to leave other feedback for me directly, you can always reach me at aj@datadoghq.com

Thanks!

**Comment by samchungy** [comment]
Answering my own question here:

I can configure a custom manager in Renovate to check the extension's version against a GitHub release version: https://github.com/DataDog/datadog-lambda-extension/releases. 

However, the nodeVersion I cannot because the versions are inlined in the changelogs https://github.com/DataDog/datadog-lambda-js/releases

**Comment by samchungy** [comment]
Okay, figured this all out.

Node Lambda Version Renovate Config:
https://github.com/DataDog/datadog-lambda-js/issues/556#issuecomment-2178418690

Lambda Extension Renovate Config:

https://github.com/samchungy/renovate-experiments/pull/10

With the given ts code:

```ts
const datadog = new Datadog(this, 'datadog', {
  apiKeySecret: datadogSecret,
  addLayers: false,
  enableDatadogLogs: false,
  flushMetricsToLogs: false,
  extensionLayerVersion: 57,
  nodeLayerVersion: 111,
});
```

```json5
{
  customManagers: [
    {
      customType: 'regex',
      fileMatch: ['test.ts'],
      matchStrings: [
        'new Datadog\\([\\S\\s]+extensionLayerVersion:\\s?(?<currentValue>\\d+)',
      ],
      packageNameTemplate: 'DataDog/datadog-lambda-extension',
      depNameTemplate: 'datadog lambda extension layer',
      datasourceTemplate: 'github-releases',
    },
  ],
}
```
