### ISSUE TITLE
git.commit.sha

### ISSUE THREAD

**Issue by tsibelman** [DataDog/datadog-cdk-constructs#239]
We noticed that you add git.commit.sha to environment variable please make this an optional behavior as it forces deployment of all lambdas even if there no other changes it significantly impacts our deployment times.

**Comment by astuyve** [comment]
Hi @tsibelman, thanks for reaching out!

We use that tag for [Source Code Integration](https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=go)
You can optionally disable it with `enableSourceCodeIntegration: false` as per the project readme.
Please let me know if this fixes your problem.

Thanks!

**Comment by tsibelman** [comment]
Thanks it what we were looking for
