### ISSUE TITLE
Support Python 3.12 runtime

### ISSUE THREAD

**Issue by PierreKiwi** [DataDog/datadog-cdk-constructs#243]
## Expected Behavior

Similar to #170 (3.10) and #205 (3.11), would be awesome to have support for Python 3.12 runtime :).

## Actual Behavior

At the moment, it is not supported so the layers got dropped because 3.12 has no match in `constants.ts`.

## Specifications

  - Datadog Lambda Layer version: v1.10.0
  
## Stacktrace
 
<img width="585" alt="image" src="https://github.com/DataDog/datadog-cdk-constructs/assets/4112727/d7c5b91f-96ea-4d16-b2ef-81248fb8e656">

**Comment by purple4reina** [comment]
Hey @PierreKiwi, thanks a ton for pointing this out. I've opened a PR https://github.com/DataDog/datadog-cdk-constructs/pull/244.

**Comment by PierreKiwi** [comment]
Thanks a lot @purple4reina !

**Comment by duncanista** [comment]
Closing due to latest release.
