### ISSUE TITLE
Serverless Monitoring for AWS Step Functions

### ISSUE THREAD

**Issue by cshields236** [DataDog/datadog-cdk-constructs#248]
Hey not sure if this is a feature request or I have have not been able to find the functionality.

Is there any way of using the StepFunction monitoring through CDK. 

[https://docs.datadoghq.com/serverless/step_functions/installation/?tab=serverlessframework](Install Serverless Monitoring for AWS Step Functions)
We run a large amount of step function workflows but currently can see that it is monitoring invocations from our forwarding of log groups 

![Screenshot 2024-02-08 at 11 39 09](https://github.com/DataDog/datadog-cdk-constructs/assets/42182485/60b4212e-cae2-48c6-b3b3-4cffc4c2b86f)

but when we enter no logs or execution information are available 

![image](https://github.com/DataDog/datadog-cdk-constructs/assets/42182485/407d3192-f137-4fb4-bc5f-f0343771cbda)

Any help or feedback would be greatly appreciated.

**Comment by lym953** [comment]
Hi @cshields236, this is on my list, and I target to finish it by the end of 2024.

**Comment by lym953** [comment]
@cshields236 Done! Doc: https://github.com/DataDog/datadog-cdk-constructs?tab=readme-ov-file#step-functions
