### ISSUE TITLE
Allow mechanism for disabling adding git hash to DD_TAGS

### ISSUE THREAD

**Issue by benjaminpottier** [DataDog/datadog-cdk-constructs#259]
The injection of the git hash into DD_TAGS for Lambda has a side effect of always breaking snapshot tests in CDK.

It would be useful to have a way to easily remove this option or maybe override it.

## Specifications

  - Datadog Lambda Layer version: 108
  - Node version: v18.16.0
  
## Stacktrace
  
```
"DD_MERGE_XRAY_TRACES": "false",
                  "DD_SERVERLESS_APPSEC_ENABLED": "false",
                  "DD_SERVERLESS_LOGS_ENABLED": "true",
                  "DD_SERVICE": "my-service",
                  "DD_SITE": "datadoghq.com",
    -             "DD_TAGS": "git.commit.sha:f46d01b57bd6466fd09375aefc23a763450b7715,git.repository_url:git@gitlab.com:foobar.git",
    +             "DD_TAGS": "git.commit.sha:6c0f1cc29efc50b1d1f87645b85c1bab8a3fb9d3,git.repository_url:git@gitlab.com:foobar.git",
                  "DD_TRACE_ENABLED": "true",
                  "OKTA_SECRET_NAME": {
                    "Fn::Join": [
                      "-",
                      [
```

**Comment by benjaminpottier** [comment]
Sorry this can probably be closed. The solution is likely to just use an escape hatch.

```typescript
const node = stack.node;
  const lambdas = node.findAll().filter((l) => l instanceof CfnFunction) as CfnFunction[];
  lambdas.forEach((lambda) => {
    lambda.addOverride('Environment.Variables.DD_TAGS', '');
  });
```

**Comment by astuyve** [comment]
Hi @benjaminpottier - thanks for reaching out!

Apart from masking these in snapshot tests, you can also disable this integration in your snapshot test environment by setting `enableSourceCodeIntegration: false` or yes, overriding that tag.

Thanks again!
