### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by ThomasP1988** [DataDog/datadog-cdk-constructs#264]
## Expected Behavior
Publishing a Go version through jsii generation

## Actual Behavior
Only Python and Node

Hi everyone,

I've tried to compile a simple go version and it seems to work, so I was wondering if there is a specific reason why you don't publish a Go package for this constructs?

I could PR something but you might want to control the credentials to publish.

**Comment by duncanista** [comment]
Hey @ThomasP1988,

Closing this, as @lym953 has added the support for this [here](https://pkg.go.dev/github.com/DataDog/datadog-cdk-constructs-go/ddcdkconstruct).

Feel free to re-open if there's any questions!
