### ISSUE TITLE
CDK construct causing Lambda segmentation error - Node20

### ISSUE THREAD

**Issue by cshields236** [DataDog/datadog-cdk-constructs#281]
## Expected Behavior
Lambdas run as normal 

## Actual Behavior
We have recently come across an error which seems to be affecting all our Lambda functions in our Sandbox environment. They all return segmentation/ connection refused errors. Example log below.

We are running Node20 Lambda functions on ARM_64.

## Example Log
![image](https://github.com/user-attachments/assets/cd309d6a-b66f-4ff2-89f8-0f96dc758662)

## CDK Config
![image](https://github.com/user-attachments/assets/18788efa-74a3-4bcd-8e17-54e785d35476)

I have downgraded to Node 18 which fixed the issue and also removed the Datadog construct from all Lambdas which allowed them to run normally. 

## Specifications

  - Datadog Lambda Layer version: 55
  - Node version: 20

**Comment by astuyve** [comment]
Hi @cshields236 - thanks for reaching out!

Can you try removing `enableDatadogASM` or setting it to false and seeing if that resolves this issue for now?
I'll get someone to take a look right away.

Thanks!
AJ

**Comment by RomainMuller** [comment]
Would it be possible to try and run the functions (Node20 + extension + `enableDatadogASM`) with `DD_LOG_LEVEL=DEBUG` in the environment? Hopefully this sheds a little more light on what is failing to start up...

**Comment by cshields236** [comment]
hey @astuyve thanks for the response, yeah seems to be that ASM issue. Have removed and can deploy for now. Hopefully a solution is found so we can continue to use ASM.

Also what is the best way to stay up to date with these bugs/ breaking issues? There's really no indication that the error would be caused by having this feature enabled and we couldn't find anything online about the issue.

**Comment by astuyve** [comment]
Thanks @cshields236 - typically we'd see someone raise a ticket in the [extension repo](https://github.com/DataDog/datadog-lambda-extension/) and not this one. Also, when we release new extension versions with bug fixes they will be listed in the release notes. V55 is from February, and although I didn't see a fix for this specific issue in the release history there's a chance it was missed.

I'm not sure what the issue here is, but I agree with @RomainMuller - please upgrade to the latest extension version (63) and enable debug logs if you can and share them in this thread or in a support ticket so that we can determine what's happening.

Thanks!
AJ

**Comment by cshields236** [comment]
Thanks for the responses @astuyve and @astuyve 

Here is the logs from `Node20`, DD version `63` and `LogLevel="debug"`

![image](https://github.com/user-attachments/assets/b077aeab-0daf-4b6c-8ff2-58ea7685fe6a)

**Comment by cshields236** [comment]
apologies that previous image was for a notice logs, will re deploy with debug and report back

**Comment by cshields236** [comment]
Hey @astuyve @RomainMuller. Heres the logs from an invocation with version 63 and debug logs. Very verbose let me know if theres anything specific that would make it easier to diagnose. 

![Screenshot 2024-08-19 at 15 36 54](https://github.com/user-attachments/assets/19df6792-2779-466e-8315-28965fa23759)

![Screenshot 2024-08-19 at 15 37 22](https://github.com/user-attachments/assets/8b5e3e74-1c21-4d37-8552-54e14a363acb)

![Screenshot 2024-08-19 at 15 37 38](https://github.com/user-attachments/assets/6c82456c-f3ad-42d2-b7ec-9b7674ab07bc)

![Screenshot 2024-08-19 at 15 37 58](https://github.com/user-attachments/assets/079e527a-3488-4374-b399-edd2f81518b7)

![Screenshot 2024-08-19 at 15 38 15](https://github.com/user-attachments/assets/6562ab24-0a45-4b08-a6ce-3f4d67ab2c08)


![Screenshot 2024-08-19 at 15 38 27](https://github.com/user-attachments/assets/4963c6e6-14f0-44b2-92df-d4695766b21a)

**Comment by astuyve** [comment]
Hi @cshields236 - thanks so much for that, we're taking a look. Did this change for you with a recent deployment of Datadog, or suddenly start happening everywhere?

**Comment by duncanista** [comment]
Hey @cshields236,

We've identified the root cause of the issue and are actively working on a fix for it.

Will keep updating as we progress!

**Comment by duncanista** [comment]
We have a fix for this and will release a new version soon.

**Comment by astuyve** [comment]
Hi @cshields236 this should be fixed in [v64](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v64).

Sorry for the inconvenience!
AJ

**Comment by cshields236** [comment]
Hey @astuyve @RomainMuller @duncanista 

Thank you for your help and prompt responses! Have re-deployed and this has solved the issue.

All the best,
Conor
