### ISSUE TITLE
Feature request: Add nodejs22.x runtime support

### ISSUE THREAD

**Issue by matt-blanchette** [DataDog/datadog-cdk-constructs#341]
## Expected Behavior

Node versions are supported up to 22

## Actual Behavior

Node versions are supported up to 20

## Specifications

  - Node version: 22

**Comment by lym953** [comment]
It depends on the lambda layer support https://github.com/DataDog/datadog-cdk-constructs/issues/341, so I'm unable to do it on CDK side for now. Thanks for creating both issues!

**Comment by lym953** [comment]
@apiarian-datadog did it! Released in v1.21.0.
