### ISSUE TITLE
Incorret environment variable name DD_LOG_INJECTION

### ISSUE THREAD

**Issue by a1ek5borodai** [DataDog/datadog-cdk-constructs#35]
[Official docs](https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs/) refers to DD_LOGS_INJECTION variable name, but DD_LOG_INJECTION is used in code.

**Comment by agocs** [comment]
Good catch. Should be a quick fix: 

https://github.com/DataDog/datadog-cdk-constructs/blob/a74403d48ddc1feec288194e7ba84b8de8b06537/src/env.ts#L13

```
export const injectLogContextEnvVar = "DD_LOG_INJECTION";
```

becomes

```
export const injectLogContextEnvVar = "DD_LOGS_INJECTION";
```

I'll coordinate a fix today.

**Comment by a1ek5borodai** [comment]
Thanks for the quick response. I was not sure which option was correct, so I didn't create a PR. For some reason with Pino the automatic injection of DD metadata into the logs does not work for me with any of these variables. But I think this is due to my custom logger settings.
