### ISSUE TITLE
feature request: add NodeJsFunction construct support

### ISSUE THREAD

**Issue by Andrapyre** [DataDog/datadog-cdk-constructs#47]
### Request

It would be great to see support for NodeJsFunction constructs in the datadog CDK. These functions make it considerably easier to manage dependencies and are the more modern way to write NodeJs functions in lambda.

**Comment by dajulia3** [comment]
Yep, lack of NodeJsFunction support is the main reason I'm not using this library right now.

**Comment by tianchu** [comment]
We are planning to support `NodeJsFunction` in the future.

Just FYI, you could also use the Datadog CI command for Lambda to set up instrumentation https://docs.datadoghq.com/serverless/installation/nodejs?tab=datadogcli.

**Comment by ajsaavedra** [comment]
Hi @Andrapyre our latest release [v0.4.0](https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v0.4.0) offers support for both NodejsFunction and PythonFunction constructs. 🎉  
I will close out this issue but feel free to let us know if you have any other issues to report with the updates that have been made.
