### ISSUE TITLE
Compatibility with cdk v2

### ISSUE THREAD

**Issue by webratz** [DataDog/datadog-cdk-constructs#51]
## Expected Behavior

The datadog-cdk-constructs can be used with the upcoming CDK v2 (release candidates already available)

## Actual Behavior

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdk@0.1.0
npm ERR! Found: constructs@10.0.5
npm ERR! node_modules/constructs
npm ERR!   constructs@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer constructs@"^3.2.27" from datadog-cdk-constructs@0.3.0
npm ERR! node_modules/datadog-cdk-constructs
npm ERR!   datadog-cdk-constructs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
The dependencies can't be resolved when using the suggested settings for v2.

## Steps to Reproduce the Problem

  1. Migrate or Setup a CDK project with v2 (https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html)
  1.  `npm install datadog-cdk-constructs`

## Specifications

  - Datadog Lambda Layer version: 
  - Node version:  v12.22.2
  
## Stacktrace
  
see actual behavior section

**Comment by hghotra** [comment]
Hi @webratz, thanks for creating this issue. This is something we're aware of and will be working on supporting this in the near future.

**Comment by jclough96** [comment]
Is there a timeline for this to be implemented? 

It seems a fairly straightforward task but would be a breaking change/major version release.

**Comment by leachj** [comment]
CDK 2.0 is now generally available. Do you have any idea about when this will be supported?

**Comment by dkamali-mc** [comment]
Can you please support CDK 2.0

**Comment by covertbert** [comment]
+1 for this. Please support CDK v2, it should be a simple upgrade

**Comment by tianchu** [comment]
Hi everyone, we are fully aware of the value of supporting CDK 2.0. It is a Q1 2022 roadmap candidate, and we will have a better answer in early Jan after our internal planning.

**Comment by ProficientBell** [comment]
This is a priority for us.  I have pulled datadog from our cdk projects until this can be completed as we migrate to 2.0

**Comment by lielran** [comment]
it seems not large refactor by this one https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html 
mostly around the dependencies and versioning of this package for backward compatibility

**Comment by msessa** [comment]
Please prioritize this issue. It is the only library blocking our migration to CDKv2

**Comment by tianchu** [comment]
Thanks for your feedback, we are committed to getting this done as a high priority in Q1!

**Comment by msessa** [comment]
@tianchu
In the hope of streamlining the process, I've submitted a PR with the required changes to support CDKv2. 
The biggest issue is probably around versioning and long-term support for CDKv1. Can be discussed in the PR.

**Comment by DarcyRaynerDD** [comment]
Thanks @msessa for your PR, it was has been very informative. Just to give an update, we're planning to refactor the codebase slightly, so we can publish parallel v1 and v2 versions of our constructs library, (rather than migrating the codebase entirely to v2), since a considerable number of users are still adopting v1.  We're going to start work on this shortly.

**Comment by msessa** [comment]
Hi @DarcyRaynerDD, glad to be of help.

Looking forward to the new version 😊

**Comment by Dachmian** [comment]
@DarcyRaynerDD Not to pile on but do you have some sort of timeline for it? Q1 can mean everything from now until end of March so really interested to know as we also want to migrate to CDK v2 and Datadog is the last construct were waiting on. 

Also just want to say that the CDK support in Datadog is awesome :D

**Comment by DarcyRaynerDD** [comment]
Hi @Dachmian. We will start working on this in the next week or so. I can't give a solid timeline for when it will be available, but I can say it is a high priority for us to get this work finished so people can fully migrate.

**Comment by lielran** [comment]
DataDog team, I must say that this one is a real blocker for us to migrate to cdk v2. 
most of our infra is using this construct.
CDK team announce months ago the migration plan and timeline and also expose beta for developers to upgrade and be ready. this is critical to be responding and ready for major upgrades. 

for example cdk-nag (one of my favorites, totally inspiring IMO) was support cdk v2 [few months ago](https://github.com/cdklabs/cdk-nag/releases/tag/v2.0.0) 

I am not sure about the resource allocation to this project but there is an [PR](https://github.com/DataDog/datadog-cdk-constructs/pull/78)  waiting for feedback for 21 days now. 
the community would love to help or at least provide some alternative (in beta mode). 


I am personally willing to push this forward, guide us on how to.

**Comment by covertbert** [comment]
@lielran while I agree that Datadog have really dropped the ball by not being prepared for this, it's not helping anyone by being *yet another person* in this thread who's giving them shit for it. It is what it is, they're clearly treating it as a number one priority now if you read the most recent messages from @DarcyRaynerDD

**Comment by mwawrusch** [comment]
> @lielran while I agree that Datadog have really dropped the ball by not being prepared for this, it's not helping anyone by being _yet another person_ in this thread who's giving them shit for it. It is what it is, they're clearly treating it as a number one priority now if you read the most recent messages from @DarcyRaynerDD

IT's been 17 days since your post, so here we go. New potential customer, would like to test datadog out with CDK.

**Comment by DarcyRaynerDD** [comment]
Hi @mwawrusch . We're in the final stages of testing v2, aiming for a release this week. You can track progress with this PR: https://github.com/DataDog/datadog-cdk-constructs/pull/84

**Comment by dan-lind** [comment]
Saw that this PR has been merged now. 
Release here:
https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-0.1.0

**Comment by covertbert** [comment]
We've updated to CDK v2 using the new Datadog construct and everything seems to be working fine. Cheers @DarcyRaynerDD!

**Comment by DarcyRaynerDD** [comment]
Thanks @covertbert, but @thedavlee did all the work. I'm going to close this issue for now. Let us know if you run into any issues.
