### ISSUE TITLE
Unable to use construct with Datadog Extension on ARM functions

### ISSUE THREAD

**Issue by deeheber** [DataDog/datadog-cdk-constructs#79]
## Expected Behavior
I should be able to update my Lambda functions to ARM and the Extension should work.

Looking at [this issue](https://github.com/DataDog/datadog-lambda-js/issues/250), it appears the `-ARM` prefix is not being applied properly to the `Datadog-Extension`'s ARN.

Initial glance at the source code didn't raise any red flags unless maybe the [`isARM` value](https://github.com/DataDog/datadog-cdk-constructs/blob/4793e68edb00bb7b624571e2a265c159bfd8e24c/src/layer.ts#L141) is always evaluating to `false`?

Below is my function's config after deploying with this construct.

<img width="1486" alt="Screen Shot 2022-01-03 at 1 23 35 PM" src="https://user-images.githubusercontent.com/12616554/147985097-7383db86-f1e4-497d-8e3b-e70630574177.png">

Any help or insight you can provide would be greatly appreciated. 🙏 

## Actual Behavior
I'm receiving errors in my Lambda Cloudwatch logs that appear to be related to the Datadog extension loading...it appears to be attempting to load an X_86 executable.

Manually updating the extension layer to ARN `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension-ARM:16` in the Lambda console got the error to go away, though I noticed when I redeployed that the layer goes back to the non arm version.

## Steps to Reproduce the Problem

  1. Updated my Lambda functions to ARM
  1. Deployed
  1. Got errors (see below) in my CloudWatch logs
  2. Updated datadog-cdk-constructions to version 0.5.0 => same issue

## Specifications

  - Datadog Lambda Layer version: nodeLayerVersion 67
  - Node version: 12
  - extensionLayerVersion: 16
  
  I'm initializing Datadog via
  ```
  const datadog = new Datadog(scope, `${stageName}-Datadog`, {
    nodeLayerVersion: 67,
    extensionLayerVersion: 16,
    apiKey: globalSecrets.datadogApiKey,
    logLevel: 'debug'
  });
  
  datadog.addLambdaFunctions(arrayOfLambdaFunctionsHere);
  ```
  
## Stacktrace

This is from my updated Lambda ARM function's CloudWatch logs.
  
```
2022-01-03T13:20:22.007-08:00 | EXTENSION Name: datadog-agent State: LaunchError Events: [] Error Type: UnknownError
-- | --
  | 2022-01-03T13:20:22.124-08:00 | START RequestId: bed92060-8704-4d2a-9313-118aa28d1415 Version: $LATEST
  | 2022-01-03T13:20:22.128-08:00 | EXTENSION Name: datadog-agent State: LaunchError Events: [] Error Type: UnknownError
  | 2022-01-03T13:20:22.128-08:00 | END RequestId: bed92060-8704-4d2a-9313-118aa28d1415
  | 2022-01-03T13:20:22.128-08:00 | REPORT RequestId: bed92060-8704-4d2a-9313-118aa28d1415 Duration: 3.39 ms Billed Duration: 4 ms Memory Size: 1024 MB Max Memory Used: 3 MB
  | 2022-01-03T13:20:22.128-08:00 | RequestId: bed92060-8704-4d2a-9313-118aa28d1415 Error: fork/exec /opt/extensions/datadog-agent: exec format error Extension.LaunchError
```

**Comment by thedavlee** [comment]
Hi @deeheber, thanks for reporting the issue. To reproduce the issue, are you updating your lambda functions to ARM using the CDK, through the AWS console or UI, or some other way?

**Comment by deeheber** [comment]
Hi @thedavlee,

Thanks for the reply. Sorry I forgot to include that detail.

We're updating our lambda functions to ARM using the CDK version 1.136.0 for all CDK packages. I don't know if it matters, but we're using the [NodeJSFunction](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html) construct.

An example of a function creation looks similar to this (I just put in `params.` in place of the actual data since I don't want to copy/paste production code in a public Github issue).

```
  import { NodejsFunction } from '@aws-cdk/aws-lambda-nodejs';
  import * as lambda from '@aws-cdk/aws-lambda';

    const myLambda = new NodejsFunction(this, `${this.stageName}-${params.name}`, {
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_12_X,
      entry: params.entry,
      handler: params.handler,
      memorySize: 1024,
      vpc: params.vpc,
      securityGroups: [params.securityGroup],
      environment: params.environment,
      bundling: {
        minify: true,
        sourceMap: true,
      },
      timeout: params.timeout
      reservedConcurrentExecutions: params.reservedConcurrentExecutions,
    });
```

We're then inputting the created lambda functions into an array that get fed into `datadog.addLambdaFunctions` code mentioned above.

I did verify via visual inspection in the AWS console that these functions are being updated to ARM.

Let me know if you need any additional info and thanks again.

**Comment by thedavlee** [comment]
@deeheber, thanks for the prompt response.

Unfortunately I wasn't able to replicate your issue, using:

- NODEJS_12_X runtime
- datadog-cdk-constructs `0.5.0`
- version `1.136.0` for all AWS CDK packages
- NodejsFunction construct
- the same extensionLayer and nodeLayer versions.

Note: datadog-cdk-constructs version `0.5.0` should definitely be used, any earlier versions will produce the exact behavior you mentioned as ARM support had yet to be fully implemented. 

Aside from double checking you're on our datadog cdk version 0.5.0, could you send your dependency tree? `npm list`

**Comment by deeheber** [comment]
Hey @thedavlee going to close this issue. Still not sure what's going on, but it's possible the issue might be on my end and out of your scope. Thanks for your help thus far. Will reopen if there's any relevant updates.
