### ISSUE TITLE
Provide configuration option for Log Scrubbing

### ISSUE THREAD

**Issue by bradleyess** [DataDog/datadog-cdk-constructs#86]
## Expected Behavior
I am able to provide a list of `DdScrubbingRule`s as props for the construct which are used to scrub log lines for sensitive information similar to the Serverless library. 

https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#log-scrubbing-optional

## Actual Behavior

There is no functionality supported for scrubbing in this library currently.

**Comment by tianchu** [comment]
I assume you use Datadog Lambda Extension (instead of the Forwarder)? If so, see https://docs.datadoghq.com/serverless/libraries_integrations/extension/#log-collection.

**Comment by bradleyess** [comment]
@icywednesdays - can you confirm the above?

**Comment by tianchu** [comment]
Closed, assuming the previously shared instruction helped.
