### ISSUE TITLE
Lambda tags not being picked up for serverless

### ISSUE THREAD

**Issue by Gotusso** [DataDog/datadog-cdk-constructs#88]
## Expected Behavior
1. Tags are provided in the cdk stack
2. Tags are available in AWS
3. Tags are available in DD

## Actual Behavior
1. Tags are provided in the cdk stack
2. Tags are available in AWS
3. Tags are **NOT** available in DD

## Steps to Reproduce the Problem

  1. Use the new CDK 2 bindings. Not sure if related
  1. Define tags on the cdk stack
```
    private prepareInstrumentation(scope, id) {
        Tags.of(this).add("service", id);
        Tags.of(this).add("env", scope.stage);
        Tags.of(this).add("version", process.env.SEED_BUILD_SERVICE_SHA);

        const apiKey = "...";
        const site = "datadoghq.eu";

        const datadog = new Datadog(this, "Datadog", {
            nodeLayerVersion: 67,
            extensionLayerVersion: 18,
            apiKey,
            site,
        });

        datadog.addLambdaFunctions(this.getAllFunctions());
    }
```
  1. Tags are available in AWS, for the cloudformation stack and all children
![Screenshot 2022-02-07 at 18 11 23](https://user-images.githubusercontent.com/692432/152837341-95c5de4e-1e1d-4309-b2e8-e2e63bda1b97.png)

  1. Tags are not available in Datadog
![Screenshot 2022-02-07 at 18 12 59](https://user-images.githubusercontent.com/692432/152837633-7dad9aff-408a-441a-adea-914016392790.png)

## Specifications

  - Datadog Lambda Layer version: 18
  - Node version: 67

**Comment by hghotra** [comment]
Hi @Gotusso , can you try using the following environment variables instead of tags: `DD_ENV`, `DD_SERVICE` and `DD_VERSION `?

**Comment by Gotusso** [comment]
@hghotra that way it picks up env and service. I cannot find version, but that might be me as I'm new with datadog

**Comment by awspathwaysqa-mc** [comment]
I'm having the same issue, 
I did add the tags as per the documentation, no luck 

`    cdk.Tags.of(this).add('env', 'prod'));
    cdk.Tags.of(this).add('service', 'backend-api');`

**Comment by DeanKamali** [comment]
I'm having the same issue,
I did add the tags as per the documentation, and it doesn't get picked up by DD 

cdk.Tags.of(this).add('env', 'prod'));
cdk.Tags.of(this).add('service', 'backend-api');

**Comment by tianchu** [comment]
@DeanKamali There are currently two ways to specify tags -- setting Lambda tags or `DD_XXX` env vars. We are in the middle of transitioning from using tags to env vars. Can you try setting env vars `DD_ENV`, `DD_SERVICE` and `DD_VERSION` on your functions?

Lambda tags will continue to work, but they only get picked up if you have the AWS and Lambda integrations enabled in your Datadog account (we need to pull the tags from our backend, since they are not directly accessible in Lambda runtime).

**Comment by adikari** [comment]
I am having the same issue. Why not add ability to set the `env`, `service` and `version` through cdk Datadog constructor? 

Something like 

```
new Datadot(this, 'Datadog', {
...
env: 'staging',
version: 1,
service: 'some-service'
})
```

Setting the env variable is fine and it seems to work. However, now I have to set it on every lambda function I have in my cdk stack.

**Comment by tianchu** [comment]
@adikari Really appreciate your feedback, that's actually what we are planning to do, stay tuned :)

**Comment by tianchu** [comment]
Closing because of https://github.com/DataDog/datadog-cdk-constructs/pull/100.
