### ISSUE TITLE
CDKV2 issue with @aws-cdk/aws-lambda-python-alpha

### ISSUE THREAD

**Issue by mattiamatrix** [DataDog/datadog-cdk-constructs#91]
Hello, 

I am having some issues in my project as I am forced to use `@aws-cdk/aws-lambda-python-alpha version `2.0.0-alpha.1`. 

https://github.com/DataDog/datadog-cdk-constructs/blob/80af4cb471081dc78d5141164ccf0ba635240f7d/v2/package.json#L61

Is it possible to relax the requirement?

**Comment by thedavlee** [comment]
Hi @mattiamatrix, thanks for raising this issue. What version of `aws-lambda-python-alpha` would work for your project?

**Comment by thedavlee** [comment]
@mattiamatrix sorry, I think I'm misunderstanding your response. Are you requesting a looser version of `@aws-cdk/aws-lambda-python-alpha`, or `aws-cdk-lib`? What are the issues in your project?

**Comment by dmccorm2** [comment]
This may be a separate issue, but I'm having this problem

`npm ERR! While resolving: infra@0.1.0
npm ERR! Found: constructs@10.0.127
npm ERR! node_modules/constructs
npm ERR!   peer constructs@"^10.0.0" from @aws-cdk/aws-lambda-python-alpha@2.22.0-alpha.0
npm ERR!   node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!     @aws-cdk/aws-lambda-python-alpha@"^2.22.0-alpha.0" from the root project
npm ERR!   peer constructs@"^10.0.0" from @aws-solutions-constructs/aws-lambda-sqs@2.5.0
npm ERR!   node_modules/@aws-solutions-constructs/aws-lambda-sqs
npm ERR!     @aws-solutions-constructs/aws-lambda-sqs@"^2.5.0" from the root project
npm ERR!   3 more (@aws-solutions-constructs/aws-sns-sqs, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! datadog-cdk-constructs@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: constructs@3.3.283
`
Can the datadog peer dependency be upgraded to use the newest constructs?

**Comment by dmccorm2** [comment]
Now I'm with @mattiamatrix , I'm also trying to use a newer AWS CDK construct. `2.22.0-alpha.0` for lambda python specifically, but if an update were to come out I'd want to use the latest. A tricky disclaimer is that

>The APIs of higher level constructs in this module are experimental and under active development. They are subject to non-backward compatible changes or removal in any future version. These are not subject to the [Semantic Versioning](https://semver.org/) model and breaking changes will be announced in the release notes. This means that while you may use them, you may need to update your source code when upgrading to a newer version of this package.

And that applies to the Python Function alpha package. Maybe the latest should always be supported since the semantic versioning "Looseness" doesn't mean a whole lot?

**Comment by sfirrin** [comment]
Hi @mattiamatrix and @dmccorm2 thanks for the report and details, I'm working on getting this fixed in https://github.com/DataDog/datadog-cdk-constructs/pull/106. That PR is not actually currently correct since it doesn't use projen properly but a fix for that is in progress

**Comment by sfirrin** [comment]
Hi again @mattiamatrix and @dmccorm2 

I've merged the PR above and included it in this new release https://github.com/DataDog/datadog-cdk-constructs/releases/tag/v2-0.3.2. Can you give it a try and let us know if you're still running into any issues?

**Comment by sfirrin** [comment]
Hi again, I'm going to close this issue for now. Please re-open and let us know if there are still any problems.

**Comment by mattiamatrix** [comment]
hello @sfirrin,

I am not sure it was fixed. When I do `npm install` I get this error
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: aws-cdk@0.1.0
npm ERR! Found: @aws-cdk/aws-lambda-python-alpha@2.25.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!   dev @aws-cdk/aws-lambda-python-alpha@"2.25.0-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-lambda-python-alpha@"^2.0.0-alpha.1" from datadog-cdk-constructs-v2@0.3.2
npm ERR! node_modules/datadog-cdk-constructs-v2
npm ERR!   dev datadog-cdk-constructs-v2@"0.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/XXX/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2022-05-27T13_42_40_178Z-debug-0.log
```

**Comment by mattiamatrix** [comment]
Please see https://semver.npmjs.com/ 
<img width="1669" alt="Screenshot 2022-05-27 at 14 52 28" src="https://user-images.githubusercontent.com/5013654/170713245-cade4f83-d4a0-44f4-ae98-dd0edb3a170b.png">

**Comment by sfirrin** [comment]
Hey, thanks for the details, apologies for the premature close. I'm reopening and we're going to look into a fix

**Comment by ddhanak** [comment]
@sfirrin we have an issue where we need to use @aws-cdk/aws-lambda-python-alpha@2.61.1-alpha.0 but due to the version pinned in the peer dependency of the construct we are forced to downgrade to `2.24.0-alpha.0`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdk@0.1.0
npm ERR! Found: @aws-cdk/aws-lambda-python-alpha@2.61.1-alpha.0
npm ERR! node_modules/@aws-cdk/aws-lambda-python-alpha
npm ERR!   peer @aws-cdk/aws-lambda-python-alpha@"2.61.1-alpha.0" from @poka-cdk/base-constructs@4.3.6-rc.1
npm ERR!   node_modules/@poka-cdk/base-constructs
npm ERR!     @poka-cdk/base-constructs@"4.3.6-rc.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-lambda-python-alpha@"^2.24.0-alpha.0" from datadog-cdk-constructs-v2@1.2.0
npm ERR! node_modules/datadog-cdk-constructs-v2
npm ERR!   peer datadog-cdk-constructs-v2@"^1.0.0" from @poka-cdk/base-constructs@4.3.6-rc.1
npm ERR!   node_modules/@poka-cdk/base-constructs
npm ERR!     @poka-cdk/base-constructs@"4.3.6-rc.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Is it possible to bump the peer dependency to the latest release?
