### ISSUE TITLE
S3 bucket uploader

### ISSUE THREAD

**Issue by ahammond** [DataDog/datadog-cdk-constructs#95]
We have an S3 bucket. We want to use the standard forwarder (https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#cloudformation) 
to push the contents of this bucket to DD.

## Expected Behavior

It should be pretty easy to snoop into this construct and directly manipulate the lambda.

## Actual Behavior

Nope. There's no easy way to subscribe the publisher lambda in here to an S3 bucket. 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Datadog Lambda Layer version: 
  - Node version: 
  
## Stacktrace
  
  ```
  Paste here
  ```

**Comment by duncanista** [comment]
🐸  Hey @ahammond!

Sorry for the late response. Thanks for creating this issue.
In order for us to triage your feature request, [creating a ticket in our support page](https://help.datadoghq.com/hc/en-us/requests/new) will help us incredibly.
You can attach this GitHub issue in the description. Please make sure set the product type to `Infrastructure` and the category as `Feature request`. This will directly send it to our engineering team where we will triage this faster!

I have to close this ticket, but feel free to re-open it if you have any questions/concerns.
Sorry for the inconvenience! 🙇🏽
