### ISSUE TITLE
make datadog cloudformation resources usable in cdk

### ISSUE THREAD

**Issue by webratz** [DataDog/datadog-cdk-constructs#96]
I'm currently working on building L1 and partially L2 CDK constructs for https://github.com/DataDog/datadog-cloudformation-resources
Is this something you would be interested in including in this project? If so i could probably add the first steps towards this, otherwise i would publish it as a separate library.

**Comment by tianchu** [comment]
Hi @webratz, sorry for the late reply and thanks for your contribution in advance! Do you have a WIP repo? I need to first have an internal conversation with the owner of https://github.com/DataDog/datadog-cloudformation-resources internally and see what they think. Maybe we can incorporate your contribution into this repo once it gains some usage and the datadog teams can commit to providing official support?

**Comment by webratz** [comment]
My progress on this has currently stalled as I'm working on other things.
But yeah, i agree it should be closely linked to https://github.com/DataDog/datadog-cloudformation-resources
If we can add directly a better spec to the DashBoard for example (eg generated from the openAPI spec) this would already be good enough for a start.
I use https://github.com/cdklabs/cdk-import to generate the L1 constructs from these definitions. Would be great of course if these were published directly by datadog

**Comment by tianchu** [comment]
@webratz I will leave this issue open for an extended period of time to see if more people express interests. For now, there isn't anything on the roadmap.

**Comment by tianchu** [comment]
Closing due to lack of activities.
